services:
    go-app:
        container_name: go-app
        build:
            context: .
            dockerfile: ./dev.dockerfile
        environment:
            PORT: "8000"
            DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
        ports:
            - "8000:8000"
        depends_on:
            - go_db
        volumes:
            - ./:/app
            - go-build-cache:/go/pkg/mod
    go_db:
        image: postgres:17.4
        container_name: go_db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
    go-build-cache: {}